language: generic

env:
  - PPA=yes
  - PPA=no

install:
  - if [ x"$PPA" == "xyes" ]; then sudo add-apt-repository ppa:pi-rho/dev -y; fi
  - sudo apt-get update -q
  - sudo apt-get install vim-nox
  - sudo pip install vim-vint

before_script:
  - vim --version
  - vint --version

script:
  - vint --color --style ./ftdetect/tmng.vim ./ftplugin/tmng.vim ./syntax/tmng.vim

