language: python
install:
  - pip install vim-vint
  - npm install -g coffee-script vimspec

before_script:
  - vim --version
  - vint --version

script:
  - vint --color --style $(git ls-files | grep -e '.vim$')
  - vimspec

